"""initial

Revision ID: 4b48d9ff3e03
Revises: 
Create Date: 2026-08-14 00:50:05.922824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b48d9ff3e03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('manager', sa.String(length=64), nullable=True),
    sa.Column('manager_tenure', sa.String(length=16), nullable=True),
    sa.Column('establish_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('target_clients', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_category'), 'funds', ['category'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_logs_sync_type'), 'sync_logs', ['sync_type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('sales', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('fund_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('code_type', sa.String(length=8), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_codes_code'), 'fund_codes', ['code'], unique=True)
    op.create_index(op.f('ix_fund_codes_fund_id'), 'fund_codes', ['fund_id'], unique=False)
    op.create_table('fund_current_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('current_tier', sa.String(length=16), nullable=False),
    sa.Column('suggested_tier', sa.String(length=16), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), nullable=True),
    sa.Column('adjusted_at', sa.DateTime(), nullable=True),
    sa.Column('manual_lock_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_current_tiers_fund_id'), 'fund_current_tiers', ['fund_id'], unique=True)
    op.create_table('fund_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_materials_fund_id'), 'fund_materials', ['fund_id'], unique=False)
    op.create_table('fund_tags',
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('fund_id', 'tag_id'),
    sa.UniqueConstraint('fund_id', 'tag_id', name='uq_fund_tag')
    )
    op.create_table('fund_tier_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('previous_tier', sa.String(length=16), nullable=False),
    sa.Column('new_tier', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_tier_histories_fund_id'), 'fund_tier_histories', ['fund_id'], unique=False)
    op.create_table('fund_performances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_code_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('return_1y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('return_3y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rank_percentile', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('aum', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('nav', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fund_code_id'], ['fund_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Daily performance metrics for each fund code'
    )
    op.create_index(op.f('ix_fund_performances_date'), 'fund_performances', ['date'], unique=False)
    op.create_index(op.f('ix_fund_performances_fund_code_id'), 'fund_performances', ['fund_code_id'], unique=False)
    op.create_table('material_download_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['fund_materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_download_logs_material_id'), 'material_download_logs', ['material_id'], unique=False)
    op.create_index(op.f('ix_material_download_logs_user_id'), 'material_download_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_download_logs_user_id'), table_name='material_download_logs')
    op.drop_index(op.f('ix_material_download_logs_material_id'), table_name='material_download_logs')
    op.drop_table('material_download_logs')
    op.drop_index(op.f('ix_fund_performances_fund_code_id'), table_name='fund_performances')
    op.drop_index(op.f('ix_fund_performances_date'), table_name='fund_performances')
    op.drop_table('fund_performances')
    op.drop_index(op.f('ix_fund_tier_histories_fund_id'), table_name='fund_tier_histories')
    op.drop_table('fund_tier_histories')
    op.drop_table('fund_tags')
    op.drop_index(op.f('ix_fund_materials_fund_id'), table_name='fund_materials')
    op.drop_table('fund_materials')
    op.drop_index(op.f('ix_fund_current_tiers_fund_id'), table_name='fund_current_tiers')
    op.drop_table('fund_current_tiers')
    op.drop_index(op.f('ix_fund_codes_fund_id'), table_name='fund_codes')
    op.drop_index(op.f('ix_fund_codes_code'), table_name='fund_codes')
    op.drop_table('fund_codes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sync_logs_sync_type'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_funds_category'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
